# Generated by Django 3.1.13 on 2021-09-01 09:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image
import parler.fields
import parler.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Forest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_trees', models.IntegerField(blank=True, null=True)),
                ('number_of_species', models.IntegerField(blank=True, null=True)),
                ('total_area', models.IntegerField(blank=True, help_text='The total area of the forest', null=True)),
                ('burned_area', models.IntegerField(blank=True, help_text='The total burned area of the forest', null=True)),
                ('occupied_area', models.IntegerField(blank=True, help_text='The total area occupied by the Establishment', null=True)),
                ('fire_year', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Forest',
                'verbose_name_plural': 'Forests',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='HotelsChain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127, verbose_name='Establishments chain name')),
            ],
            options={
                'verbose_name': 'Chain',
                'verbose_name_plural': 'Chains',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('type', models.CharField(choices=[('OLD', 'Old'), ('NEW', 'New')], max_length=3)),
                ('file', filer.fields.image.FilerImageField(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_image', to=settings.FILER_IMAGE_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Establishment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.CharField(blank=True, max_length=127, null=True, verbose_name='booking.com ID')),
                ('tripadvisor_id', models.CharField(blank=True, max_length=127, null=True, verbose_name='tripadvisor.com ID')),
                ('built_year', models.IntegerField(blank=True, null=True)),
                ('type', models.IntegerField(choices=[(10, 'Hotel'), (20, 'Mine'), (30, 'Other')])),
                ('hotels_chain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.hotelschain')),
            ],
            options={
                'verbose_name': 'Establishment',
                'verbose_name_plural': 'Establishments',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(blank=True, max_length=255, null=True, verbose_name='Street name')),
                ('number', models.IntegerField(blank=True, null=True)),
                ('city', models.CharField(max_length=127, verbose_name='City')),
                ('country', models.CharField(max_length=127, verbose_name='Country')),
                ('establishment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='main.establishment')),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
            },
        ),
        migrations.CreateModel(
            name='ForestTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(blank=True, max_length=127, null=True, verbose_name='Name')),
                ('type_of_tree', models.CharField(blank=True, max_length=127, null=True, verbose_name='Type of trees')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='main.forest')),
            ],
            options={
                'verbose_name': 'Forest Translation',
                'db_table': 'main_forest_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='EstablishmentTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=127, verbose_name='Establishment name')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='main.establishment')),
            ],
            options={
                'verbose_name': 'Establishment Translation',
                'db_table': 'main_establishment_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
