# Generated by Django 3.1.13 on 2021-08-04 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127, verbose_name='Hotels chain name')),
            ],
        ),
        migrations.CreateModel(
            name='Forest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=127, null=True, verbose_name='Name')),
                ('type_of_tree', models.CharField(blank=True, max_length=127, null=True, verbose_name='Type of trees')),
                ('number_of_trees', models.IntegerField(blank=True, null=True)),
                ('number_of_species', models.IntegerField(blank=True, null=True)),
                ('total_area', models.IntegerField(blank=True, help_text='The total area of the forest', null=True)),
                ('burned_area', models.IntegerField(blank=True, help_text='The total burned area of the forest', null=True)),
                ('occupied_area', models.IntegerField(blank=True, help_text='The total area occupied by the hotel', null=True)),
                ('fire_year', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127, verbose_name='Hotel name')),
                ('booking_id', models.CharField(blank=True, max_length=127, null=True, verbose_name='booking.com ID')),
                ('tripadvisor_id', models.CharField(blank=True, max_length=127, null=True, verbose_name='tripadvisor.com ID')),
                ('built_year', models.IntegerField(blank=True, null=True)),
                ('chain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.chain')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(blank=True, max_length=255, null=True, verbose_name='Street name')),
                ('number', models.IntegerField(blank=True, null=True)),
                ('city', models.CharField(max_length=127, verbose_name='City')),
                ('country', models.CharField(max_length=127, verbose_name='Country')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='main.hotel')),
            ],
        ),
    ]
